trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore ahma_quiz4_dotnet.csproj
  displayName: 'Restore'

- script: dotnet build ahma_quiz4_dotnet.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Build'

- script: dotnet publish ahma_quiz4_dotnet.csproj --configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)" --no-build
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'